### ISSUE TITLE
Sd Copy

### ISSUE THREAD

**Issue by sohamganatra123** [LarsMichelsen/sd-autocopy#1]
Hi 
This seems it can copy data from a particular sd card ,
Is there any way we can copy any sd card / card inserted to be copied? 

Kindly revert , 

Thanks

**Comment by LarsMichelsen** [comment]
You may remove these lines to disable filtering of cards:

```
if ! echo "$HANDLED_SERIALS" | grep $ID_SERIAL >/dev/null 2>&1; then
    logger -t sd-autocopy "Got unhandled serial, skipping (Serial: $ID_SERIAL)"
    exit 1
fi
```

**Comment by sohamganatra123** [comment]
thanks 

this worked.
